### PR TITLE
Use move construction for boost::process::detail::cmd::operator()

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

**Comment by klemens-morgenstern** [comment]
That actually introduces an additional copy.

**Comment by jonesmz** [comment]
Elaborate please?

I don't see how this could introduce an additional copy. At worse its the same number.

**Comment by klemens-morgenstern** [comment]
Ah you're right. You have one copy and one move or two moves. Currently you have one of either, plus passing a reference.

**Comment by jonesmz** [comment]
I'm deleting this branch. You take too long to do anything, and you close PRs for reasons that you later admit are wrong, but then leave the PR closed instead of doing anything about being wrong.

**Pull request closed without merging**
