### PR TITLE
Make constructor for codecvt_category_t constexpr

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

**Comment by klemens-morgenstern** [comment]
Doesn't work for C++11

**Comment by jonesmz** [comment]
Why are you supporting a 9 year old language?

**Comment by klemens-morgenstern** [comment]
LTS

**Comment by jonesmz** [comment]
Ok. I suppose that's not a big problem for me.

Can you leave this patch open, and tag it with some kind of "Requires C++14" tag?

Unless you don't want the change for other reasons, of course.

**Comment by klemens-morgenstern** [comment]
It is rather unlikely that I will build a C++14 version of this at any point. A C++20 boost.process2 is much more likely, i.e. a reference implementation of P1750R1.

**Comment by jonesmz** [comment]
Ok.

**Pull request closed without merging**
