### PR TITLE
Changes required to compile with new Asio executors model

### PR DESCRIPTION
**Pull request by chriskohlhoff**
Targeted at 1.74

### CODE REVIEW

**Comment by klemens-morgenstern** [comment]
That broke my windows build. If I only include `netfwd.hpp` the `any_io_executor` isn't defined. How can I solve that, where do the config macros come from?

**Comment by chriskohlhoff** [comment]
FYI I haven't yet merged the `netfwd.hpp` change to the `master` branch of asio. Just waiting for a few more tests to cycle before I merge it.

**Comment by klemens-morgenstern** [comment]
Oh that makes sense - currently running on the `develop` branch?

**Comment by chriskohlhoff** [comment]
Yep. If you're testing your windows build locally maybe you can check out asio on `develop` just to double check it's all ok. Otherwise, I will probably do the merge to asio `master` in 6-8 hours or so.

**Comment by klemens-morgenstern** [comment]
Yeah, works now, please ping me once merged.

**Comment by chriskohlhoff** [comment]
Done.

**Pull request merged**
