### PR TITLE
Reserve space in string for later concatenation

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

**Comment by klemens-morgenstern** [comment]
Looks like a good idea, but doesn't compile. Please note that I the official standard for this library is still C++11

**Comment by jonesmz** [comment]
I changed it to no longer require auto parameters in lambdas.

Should compile with c++11 now.

**Comment by jonesmz** [comment]
Your continuous integration is broken.

apt-get install failed
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install valgrind python-yaml gcc-5 g++-5 clang" failed and exited with 100 during .

**Comment by klemens-morgenstern** [comment]
This is still C++14: `[first = &value.front()]`.

**Comment by jonesmz** [comment]
Fixed

**Comment by jonesmz** [comment]
it's been 11 months since i opened this PR. I'm closing it and deleting my fork of boost process.

**Pull request closed without merging**
