### PR TITLE
Fix cross-compile linux->mingw

### PR DESCRIPTION
**Pull request by orgads**
Headers are lower case.

### CODE REVIEW

**Comment by Martchus** [comment]
I've just ran into this problem as well. It would be great if the patch could be merged. I can confirm that it works.

**Comment by xantares** [comment]
+1 cc @klemens-morgenstern

**Comment by orgads** [comment]
Rebased.

**Comment by klemens-morgenstern** [comment]
Has this been tested on windows for native compiles?

**Comment by orgads** [comment]
Yes

**Comment by xantares** [comment]
on native windows the filesystem is case-insensitive so either works but not on linux

**Pull request merged**
