### PR TITLE
Use = default for default constructor

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

**Comment by SiggyBar** [comment]
Commit `8541cae` causes this compilation error for Visual C++ 14.1 (and 14.2):

`boost\include\boost/process/child.hpp(35): error C2600: 'boost::process::child::child': cannot define a compiler-generated special member function (must be declared in the class first)`

The same can be seen here:
https://ci.appveyor.com/project/klemens-morgenstern/boost-process/branch/develop

**Comment by jonesmz** [comment]
That... Seems like a compiler bug, given its declared and defined in the class only?

**Comment by SiggyBar** [comment]
I created a self-contained repro case and posted it to the Visual Studio Developer Community:
https://developercommunity.visualstudio.com/content/problem/909914/unexpected-compilation-error-for-compiler-generate.html

**Comment by Naios** [comment]
See #152

**Pull request merged**
